apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: ntpd
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          app: ntpd
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                      - ntpd
                topologyKey: "kubernetes.io/hostname"
        containers:
        - name: ntpd
          image: npflan/ntpd:v4
          resources:
            limits:
              memory: 100M
          livenessProbe:
            exec:
              command:
              - python3
              - /usr/local/probe/ntpd_probe.py
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
              - python3
              - /usr/local/probe/ntpd_probe.py
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 5
- kind: Service
  apiVersion: v1
  metadata:
    name: ntpd
  spec:
    type: NodePort
    selector:
      app: ntpd
    ports:
      - protocol: UDP
        port: 123
        targetPort: 123
